Refactor moving css for result card and results layout
SOFTENG310-TEAM-3/MunchMatch pull request #68
Opened 2023-09-26 21:51 UTC by mhardy88

I have moved the css attributes that are specific to the resultCard.jsx and resultsLayout.jsx to their own specific css files

2023-09-26 22:26 UTC, arielyxw requested changes
Good work on the refactor, a couple minor suggestions to look at :)

2023-09-26 22:26 UTC, arielyxw commented on munch-match/src/components/resultCard.module.css
> +.buttonD {
The naming here could be more descriptive. Just ".button" as a duplicate variable name could also work since we are specifying the module it is from.

2023-09-26 22:26 UTC, arielyxw commented on munch-match/src/components/resultsLayout.module.css
> +.buttonRL {
Similarly here to the previous comment

2023-09-26 22:55 UTC, Jackson-Schofield approved these changes
All comments fixed and issues resolved.
LGTM

2023-09-26 22:56 UTC, merged

2023-10-08 01:39 UTC, boxy8 commented
Closes #64